### ISSUE TITLE
Исправить url

### ISSUE THREAD

**Issue by lich906** [RoboutGulman/necromunda-gang-manager-frontend#1]
https://github.com/RoboutGulman/necromunda-gang-manager-frontend/blob/master/src/request/api/fighterType/getFighterTypes.ts#L7-L8

Костыль с `..` лучше убрать. В классе ApiRequest можно передать в fetch `window.location.origin + this._url` вместо `this._url`

**Comment by RoboutGulman** [comment]
Исправил
